/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Warmup
         * @description 页面打开时由前端调用：后台预热模型连接与前缀缓存，立即返回；有效期内重复调用不会再发请求。
         */
        post: operations["warmup_api_warmup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Turn */
        post: operations["post_turn_api_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Paper
         * @description 手动编辑：应用补丁并立即返回新修订；内容被改的题状态回到"待核验"，同时发起一个复核运行（`review_run_id`）。
         */
        patch: operations["patch_paper_api_sessions__session_id__paper_patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Paper */
        post: operations["undo_paper_api_sessions__session_id__paper_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redo Paper */
        post: operations["redo_paper_api_sessions__session_id__paper_redo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Paper */
        post: operations["restore_paper_api_sessions__session_id__paper_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper History */
        get: operations["paper_history_api_sessions__session_id__paper_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/revisions/{rev}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper At */
        get: operations["paper_at_api_sessions__session_id__paper_revisions__rev__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/paper/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper Diff */
        get: operations["paper_diff_api_sessions__session_id__paper_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/figures/{figure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paper Figure
         * @description 试卷里某个图形的 SVG（预览与导出共用同一份渲染）。
         */
        get: operations["paper_figure_api_sessions__session_id__figures__figure_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge Refs
         * @description 知识点的教师可读名称与位置，用于在题目旁显示"涉及：小数加减法（四下·第一单元）"。
         */
        get: operations["knowledge_refs_api_knowledge_refs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Paper File
         * @description 导出当前试卷。`inline=true` 用于页面内预览（PDF 直接嵌入）；警告（缺字、图无法绘制等）放在 `X-Export-Warnings`。
         */
        post: operations["export_paper_file_api_sessions__session_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Checkpoint */
        post: operations["answer_checkpoint_api_runs__run_id__checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Runs */
        get: operations["debug_runs_api_debug_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Run */
        get: operations["debug_run_api_debug_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Events */
        get: operations["debug_events_api_debug_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Stream
         * @description 调试台的实时事件流：与用户端同一协议，但包含 debug 可见性的事件（span、模型调用、检索）。
         */
        get: operations["debug_stream_api_debug_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/kp/{kp_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Kp
         * @description 图检索视图里点击节点：知识点说明、掌握要求、典型错误。
         */
        get: operations["debug_kp_api_debug_kp__kp_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/badcases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Badcases */
        get: operations["debug_badcases_api_debug_badcases_get"];
        put?: never;
        /**
         * Debug Add Badcase
         * @description 把一次运行里发现的坏例子写入 Badcase 簿（YAML 文件，之后按根因类别修复并转成回归用例）。
         */
        post: operations["debug_add_badcase_api_debug_badcases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Metrics */
        get: operations["debug_metrics_api_debug_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "generate" | "paper" | "review";
        /** AddItem */
        AddItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_item";
            /** Section Id */
            section_id: string;
            item: components["schemas"]["Item"];
            /** Index */
            index?: number | null;
        };
        /** AddSection */
        AddSection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_section";
            section: components["schemas"]["Section"];
            /** Index */
            index?: number | null;
        };
        /** AggregateMetrics */
        AggregateMetrics: {
            /** N Runs */
            n_runs: number;
            success_rate: components["schemas"]["Proportion"];
            trace_complete: components["schemas"]["Proportion"];
            e2e_ms: components["schemas"]["Quantiles"];
            first_feedback_ms: components["schemas"]["Quantiles"];
            /** Cache Hit Ratio */
            cache_hit_ratio: number | null;
            cost_per_run: components["schemas"]["Quantiles"];
            llm_calls_per_run: components["schemas"]["Quantiles"];
            llm_error_rate: components["schemas"]["Proportion"];
            schema_retry_rate: components["schemas"]["Proportion"];
            tokens_per_run: components["schemas"]["Quantiles"];
        };
        /**
         * AnswerPlacement
         * @enum {string}
         */
        AnswerPlacement: "inline" | "appendix";
        /** AttachmentRef */
        AttachmentRef: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
        };
        /** Badcase */
        Badcase: {
            /** Run Id */
            run_id: string;
            /** Item Id */
            item_id?: string | null;
            /**
             * Input
             * @default
             */
            input: string;
            /** Problem */
            problem: string;
            /**
             * Expected
             * @default
             */
            expected: string;
            /**
             * Root Cause
             * @enum {string}
             */
            root_cause: "U" | "P" | "R" | "W" | "V" | "B" | "E" | "X" | "S" | "K" | "UX";
            /**
             * Severity
             * @default S2
             * @enum {string}
             */
            severity: "S1" | "S2" | "S3";
            /**
             * Stage
             * @default
             */
            stage: string;
            /** Id */
            id: string;
            /** Created At */
            created_at: number;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "fixed" | "wontfix";
            /**
             * Fix Commit
             * @default
             */
            fix_commit: string;
            /**
             * Regression Case
             * @default
             */
            regression_case: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * BadcaseIn
         * @description 调试台提交的坏例子。输入与观察到的问题由人填写；运行 / 题目由调试台带上。
         */
        BadcaseIn: {
            /** Run Id */
            run_id: string;
            /** Item Id */
            item_id?: string | null;
            /**
             * Input
             * @default
             */
            input: string;
            /** Problem */
            problem: string;
            /**
             * Expected
             * @default
             */
            expected: string;
            /**
             * Root Cause
             * @enum {string}
             */
            root_cause: "U" | "P" | "R" | "W" | "V" | "B" | "E" | "X" | "S" | "K" | "UX";
            /**
             * Severity
             * @default S2
             * @enum {string}
             */
            severity: "S1" | "S2" | "S3";
            /**
             * Stage
             * @default
             */
            stage: string;
        };
        /** Body_post_turn_api_sessions__session_id__turns_post */
        Body_post_turn_api_sessions__session_id__turns_post: {
            /**
             * Text
             * @default
             */
            text: string;
            /** Images */
            images?: string[] | null;
        };
        /** Brief */
        Brief: {
            action?: components["schemas"]["Slot_Action_"];
            scope?: components["schemas"]["Scope"];
            count?: components["schemas"]["Slot_int_"] | null;
            difficulty?: components["schemas"]["Slot_list_int__"] | null;
            kinds?: components["schemas"]["Slot_list_ItemKind__"] | null;
            tier_mix?: components["schemas"]["Slot_dict_Tier__float__"] | null;
            source?: components["schemas"]["Slot_SourceMode_"];
            scenes?: components["schemas"]["Slot_list_str__"] | null;
            constraints?: components["schemas"]["Slot_list_str__"] | null;
            target_lesson?: components["schemas"]["Slot_str_"] | null;
            /** References */
            references?: components["schemas"]["ReferenceItem"][];
            paper?: components["schemas"]["PaperSpec"] | null;
            /** Assumptions */
            assumptions?: string[];
        };
        /** CheckResult */
        CheckResult: {
            /** Name */
            name: string;
            status: components["schemas"]["CheckStatus"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "pass" | "warn" | "fail" | "skip";
        /** CheckpointAnswer */
        CheckpointAnswer: {
            /** Answer */
            answer?: {
                [key: string]: unknown;
            };
        };
        /** CheckpointRequested */
        CheckpointRequested: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "checkpoint.requested";
            /** Checkpoint Id */
            checkpoint_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "clarify" | "blueprint" | "samples" | "confirm";
            /** Prompt */
            prompt: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            }[];
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * Chip
         * @description 展示在结果顶部的"本次假设"芯片（教师语言，可点击修改）。
         */
        Chip: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "user" | "inferred" | "default";
        };
        /** ClarifyOption */
        ClarifyOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * ClarifyRequest
         * @description 一次只问一个问题，带 2～4 个可点选项（PRD FR-3）。
         */
        ClarifyRequest: {
            /** Prompt */
            prompt: string;
            /** Options */
            options?: components["schemas"]["ClarifyOption"][];
        };
        /**
         * Combo
         * @description 一个知识点组合候选（"串联"的单位）。
         */
        Combo: {
            /** Kp Ids */
            kp_ids: string[];
            /** Score */
            score: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** DebugRunDetail */
        DebugRunDetail: {
            run: components["schemas"]["Run"];
            metrics: components["schemas"]["RunMetrics"];
            /** N Events */
            n_events: number;
            /**
             * Input Text
             * @default
             */
            input_text: string;
        };
        /** DebugRunItem */
        DebugRunItem: {
            run: components["schemas"]["Run"];
            metrics: components["schemas"]["RunMetrics"];
            /**
             * Input Text
             * @default
             */
            input_text: string;
        };
        /** EditIntent */
        EditIntent: {
            /** Target */
            target: string;
            /** Instruction */
            instruction: string;
        };
        /**
         * ErrorInfo
         * @description 可序列化的错误信息（进入事件与运行记录）。`message` 已脱敏；`user_message` 是教师语言。
         */
        ErrorInfo: {
            /** Code */
            code: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * User Message
             * @default
             */
            user_message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "pdf" | "docx" | "md" | "tex";
        /**
         * ExportHeader
         * @description 页眉信息；留空则取试卷 `meta` 里的同名键，再没有就留空（学生版自动给姓名 / 班级 / 得分的填写线）。
         */
        ExportHeader: {
            /**
             * School
             * @default
             */
            school: string;
            /**
             * Class Name
             * @default
             */
            class_name: string;
            /**
             * Date
             * @default
             */
            date: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Name Line
             * @default true
             */
            name_line: boolean;
        };
        /** ExportOptions */
        ExportOptions: {
            /** @default pdf */
            format: components["schemas"]["ExportFormat"];
            /** @default student */
            version: components["schemas"]["ExportVersion"];
            /**
             * Include Solution
             * @default true
             */
            include_solution: boolean;
            /** @default appendix */
            answers: components["schemas"]["AnswerPlacement"];
            /**
             * Mark Review
             * @default true
             */
            mark_review: boolean;
            header?: components["schemas"]["ExportHeader"];
        };
        /**
         * ExportVersion
         * @enum {string}
         */
        ExportVersion: "teacher" | "student";
        /**
         * FigureSpec
         * @description 图形的结构化规格；渲染为 SVG（M6 细化各类型）。
         */
        FigureSpec: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Alt
             * @default
             */
            alt: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Weight */
            weight?: number | null;
        };
        /**
         * GraphNode
         * @description 检索图中的节点（调试台"图检索视图"直接绘制）。
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Grade */
            grade?: number | null;
            /** Semester */
            semester?: string | null;
            /**
             * Domain
             * @default
             */
            domain: string;
            /**
             * Role
             * @default candidate
             * @enum {string}
             */
            role: "anchor" | "candidate" | "selected" | "context";
            /** Score */
            score?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
            /** Chalkbase Version */
            chalkbase_version: string;
            /** Data Version */
            data_version: string;
            /** Profile */
            profile: string;
            /** Llm Mode */
            llm_mode: string;
            /** Models */
            models?: {
                [key: string]: string;
            };
        };
        /** Item */
        Item: {
            /** Id */
            id: string;
            kind: components["schemas"]["ItemKind"];
            /** Stem */
            stem: string;
            /** Options */
            options?: string[];
            /**
             * Answer
             * @default
             */
            answer: string;
            /** Answer Value */
            answer_value?: unknown | null;
            /**
             * Solution
             * @default
             */
            solution: string;
            /** Kp Ids */
            kp_ids?: string[];
            /**
             * Difficulty
             * @default 3
             */
            difficulty: number;
            /** @default consolidate */
            tier: components["schemas"]["Tier"];
            /** Score */
            score?: number | null;
            /** Figures */
            figures?: components["schemas"]["FigureSpec"][];
            provenance?: components["schemas"]["Provenance"];
            verification?: components["schemas"]["Verification"];
            /**
             * Rev
             * @default 1
             */
            rev: number;
        };
        /** ItemChange */
        ItemChange: {
            /** Item Id */
            item_id: string;
            /**
             * Change
             * @enum {string}
             */
            change: "added" | "removed" | "changed" | "moved";
            /** Number Before */
            number_before?: number | null;
            /** Number After */
            number_after?: number | null;
            /** Fields */
            fields?: string[];
        };
        /**
         * ItemDelivered
         * @description 一道题通过核验、可以给教师看了（1.2 新增）。整份试卷要等全部完成才装配成修订；
         *     这个事件让用户端在此之前就能逐题上屏（PRD 原则 2：先给看得见的结果）。后续核验状态变化仍由 `item.status` 报告。
         */
        ItemDelivered: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "item.delivered";
            item: components["schemas"]["Item"];
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "choice" | "fill" | "calc" | "judge" | "application" | "open";
        /** ItemStatus */
        ItemStatus: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "item.status";
            /** Item Id */
            item_id: string;
            status: components["schemas"]["VerifyStatus"];
            /** Checks */
            checks?: components["schemas"]["CheckResult"][];
        };
        /**
         * KPDetail
         * @description 知识点详情（供 LLM 理解"这个知识点具体教什么、学生常错什么"）。
         */
        KPDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Grade */
            grade?: number | null;
            /** Semester */
            semester?: string | null;
            /**
             * Domain
             * @default
             */
            domain: string;
            /** Lesson Id */
            lesson_id?: string | null;
            /** Lesson Title */
            lesson_title?: string | null;
            /** Unit Title */
            unit_title?: string | null;
            /** Aliases */
            aliases?: string[];
            /**
             * Thread
             * @default
             */
            thread: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Mastery Level
             * @default
             */
            mastery_level: string;
            /** Typical Errors */
            typical_errors?: string[];
            /**
             * Is Assessable
             * @default true
             */
            is_assessable: boolean;
        };
        /** KPRef */
        KPRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Grade */
            grade?: number | null;
            /** Semester */
            semester?: string | null;
            /**
             * Domain
             * @default
             */
            domain: string;
            /** Lesson Id */
            lesson_id?: string | null;
            /** Lesson Title */
            lesson_title?: string | null;
            /** Unit Title */
            unit_title?: string | null;
        };
        /** LLMCall */
        LLMCall: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default debug */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "llm.call";
            record: components["schemas"]["LLMCallRecord"];
        };
        /**
         * LLMCallRecord
         * @description 一次模型调用的完整记录。调试台的"步骤检查器"、E2/D5/E1 指标都读它。
         */
        LLMCallRecord: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Model */
            model: string;
            /** Profile */
            profile: string;
            /**
             * Purpose
             * @default
             */
            purpose: string;
            prompt?: components["schemas"]["PromptRef"] | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Messages */
            messages?: {
                [key: string]: unknown;
            }[];
            /**
             * Response Text
             * @default
             */
            response_text: string;
            /**
             * Reasoning Text
             * @default
             */
            reasoning_text: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            /** Finish Reason */
            finish_reason?: string | null;
            usage?: components["schemas"]["Usage"];
            /** Ttfb Ms */
            ttfb_ms?: number | null;
            /** Ttft Ms */
            ttft_ms?: number | null;
            /**
             * Total Ms
             * @default 0
             */
            total_ms: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /** Cost */
            cost?: number | null;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /**
             * From Cassette
             * @default false
             */
            from_cassette: boolean;
            error?: components["schemas"]["ErrorInfo"] | null;
        };
        /** Message */
        Message: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentRef"][];
            /** Run Id */
            run_id?: string | null;
            /** Ts */
            ts: number;
        };
        /** MessageDelta */
        MessageDelta: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.delta";
            /** Message Id */
            message_id: string;
            /** Text */
            text: string;
        };
        /** MessageDone */
        MessageDone: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.done";
            /** Message Id */
            message_id: string;
            /** Text */
            text: string;
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system";
        /** ModelStat */
        ModelStat: {
            /** Model */
            model: string;
            /** Role */
            role: string;
            /** Calls */
            calls: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Cached Tokens */
            cached_tokens: number;
            /** Cache Hit Ratio */
            cache_hit_ratio: number | null;
            /** Cost */
            cost: number | null;
            /** Ttft P50 Ms */
            ttft_p50_ms: number | null;
            /** Total P50 Ms */
            total_p50_ms: number | null;
            /** Retries */
            retries: number;
            /** Errors */
            errors: number;
        };
        /** MoveItem */
        MoveItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move_item";
            /** Item Id */
            item_id: string;
            /** Section Id */
            section_id: string;
            /** Index */
            index?: number | null;
        };
        /**
         * Origin
         * @enum {string}
         */
        Origin: "user" | "inferred" | "default";
        /** Paper */
        Paper: {
            /** Id */
            id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Rev
             * @default 0
             */
            rev: number;
            /** Sections */
            sections?: components["schemas"]["Section"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** PaperDiff */
        PaperDiff: {
            /**
             * Title Changed
             * @default false
             */
            title_changed: boolean;
            /** Meta Changed */
            meta_changed?: string[];
            /**
             * Sections Changed
             * @default false
             */
            sections_changed: boolean;
            /** Items */
            items?: components["schemas"]["ItemChange"][];
        };
        /** PaperHistory */
        PaperHistory: {
            /** Revisions */
            revisions: components["schemas"]["Revision"][];
            /** Head Rev */
            head_rev: number;
            /** Can Undo */
            can_undo: boolean;
            /** Can Redo */
            can_redo: boolean;
        };
        /**
         * PaperPatchBody
         * @description 手动编辑：一组补丁（原子）。`base_rev` 是客户端看到的版本，用于发现别处的内容修改。
         */
        PaperPatchBody: {
            /** Base Rev */
            base_rev?: number | null;
            /** Ops */
            ops: (components["schemas"]["AddSection"] | components["schemas"]["RemoveSection"] | components["schemas"]["AddItem"] | components["schemas"]["RemoveItem"] | components["schemas"]["ReplaceField"] | components["schemas"]["MoveItem"] | components["schemas"]["SetTitle"] | components["schemas"]["SetMeta"])[];
        };
        /** PaperPatched */
        PaperPatched: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paper.patch";
            /** Paper Id */
            paper_id: string;
            /** Rev */
            rev: number;
            /** Ops */
            ops?: {
                [key: string]: unknown;
            }[];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** PaperSpec */
        PaperSpec: {
            /** Duration Min */
            duration_min?: number | null;
            /** Total Score */
            total_score?: number | null;
            /** Structure */
            structure?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * PaperUpdate
         * @description 一次修改（手改 / 撤销 / 重做 / 回退）的结果。`review_run_id` 非空时，订阅该运行的事件可看到核验状态更新。
         */
        PaperUpdate: {
            paper: components["schemas"]["Paper"];
            revision: components["schemas"]["Revision"];
            /** Warnings */
            warnings?: string[];
            /** Review Run Id */
            review_run_id?: string | null;
            /**
             * Can Undo
             * @default false
             */
            can_undo: boolean;
            /**
             * Can Redo
             * @default false
             */
            can_redo: boolean;
        };
        /** Progress */
        Progress: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
            /** Label */
            label: string;
            /** Current */
            current?: number | null;
            /** Total */
            total?: number | null;
        };
        /** PromptRef */
        PromptRef: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Hash */
            hash: string;
            /**
             * Prefix Hash
             * @default
             */
            prefix_hash: string;
            /** Segments */
            segments?: components["schemas"]["SegmentInfo"][];
        };
        /** Proportion */
        Proportion: {
            /** K */
            k: number;
            /** N */
            n: number;
            /** P */
            p: number | null;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
        };
        /** Provenance */
        Provenance: {
            /** @default novel */
            source: components["schemas"]["Source"];
            /** Archetype Ids */
            archetype_ids?: string[];
            /** Reference Ids */
            reference_ids?: string[];
            /** Run Id */
            run_id?: string | null;
            /** Model */
            model?: string | null;
        };
        /** Quantiles */
        Quantiles: {
            /** N */
            n: number;
            /** P50 */
            p50: number | null;
            /** P95 */
            p95: number | null;
            /** Mean */
            mean: number | null;
        };
        /**
         * ReferenceItem
         * @description 来自照片或用户粘贴的题：既是"学生做过什么"的上下文，也是防雷同集合。
         */
        ReferenceItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Kp Ids */
            kp_ids?: string[];
            /** Difficulty */
            difficulty?: number | null;
            kind?: components["schemas"]["ItemKind"] | null;
            /**
             * Has Figure
             * @default false
             */
            has_figure: boolean;
            /**
             * Figure Desc
             * @default
             */
            figure_desc: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** RemoveItem */
        RemoveItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_item";
            /** Item Id */
            item_id: string;
        };
        /** RemoveSection */
        RemoveSection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_section";
            /** Section Id */
            section_id: string;
        };
        /** ReplaceField */
        ReplaceField: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "replace_field";
            /** Item Id */
            item_id: string;
            /** Field */
            field: string;
            /** Value */
            value: unknown;
        };
        /** RestoreBody */
        RestoreBody: {
            /** Rev */
            rev: number;
        };
        /**
         * RetrievalPayload
         * @description 一次知识检索 / 规划步骤的可视化载荷（事件 `retrieval.result`）。
         */
        RetrievalPayload: {
            /** Step */
            step: string;
            /**
             * Query
             * @default
             */
            query: string;
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
            /** Combos */
            combos?: components["schemas"]["Combo"][];
            /** Notes */
            notes?: string[];
        };
        /** RetrievalResult */
        RetrievalResult: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default debug */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "retrieval.result";
            payload: components["schemas"]["RetrievalPayload"];
        };
        /**
         * Revision
         * @description 试卷的一条修订。历史是线性的、只增不删；撤销 / 重做 / 回退也是新增修订（内容取自某个更早的"逻辑版本"）。
         *
         *     - `logical`：这条修订所代表的"逻辑版本"。edit / restore 是它自己；undo / redo 是被恢复的那个逻辑版本；
         *       review（后台复核只更新核验状态）与它所复核的逻辑版本相同，因此对撤销栈是透明的。
         *     - `parent`：仅 edit / restore，它所基于的逻辑版本（撤销沿着 parent 往回走）。
         *     - `redo`：此刻的重做栈（逻辑版本号，栈顶在前）；任何新的 edit / restore 都会清空它。
         *     未填写（None）的 `logical / parent / redo` 由存储层按 `kind` 补全，调用方通常只需给出 `kind`。
         */
        Revision: {
            /** Paper Id */
            paper_id: string;
            /** Rev */
            rev: number;
            /** Author */
            author: string;
            /** Run Id */
            run_id?: string | null;
            /** Ts */
            ts: number;
            /** Patch */
            patch?: {
                [key: string]: unknown;
            }[];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Kind
             * @default edit
             * @enum {string}
             */
            kind: "edit" | "undo" | "redo" | "restore" | "review";
            /** Logical */
            logical?: number | null;
            /** Parent */
            parent?: number | null;
            /** Redo */
            redo?: number[] | null;
        };
        /**
         * Route
         * @enum {string}
         */
        Route: "generate" | "paper" | "edit" | "ask" | "export" | "offtopic";
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Message Id */
            message_id?: string | null;
            /** Pipeline */
            pipeline: string;
            /** @default created */
            status: components["schemas"]["RunStatus"];
            /** Created At */
            created_at: number;
            /** Started At */
            started_at?: number | null;
            /** Finished At */
            finished_at?: number | null;
            error?: components["schemas"]["ErrorInfo"] | null;
            /** Tags */
            tags?: string[];
            /** State */
            state?: {
                [key: string]: unknown;
            };
            /** Checkpoint */
            checkpoint?: {
                [key: string]: unknown;
            } | null;
        };
        /** RunFinished */
        RunFinished: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.finished";
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed" | "cancelled";
            error?: components["schemas"]["ErrorInfo"] | null;
        };
        /** RunMetrics */
        RunMetrics: {
            /** Run Id */
            run_id: string;
            /** Status */
            status?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** E2E Ms */
            e2e_ms?: number | null;
            /** First Feedback Ms */
            first_feedback_ms?: number | null;
            /**
             * N Events
             * @default 0
             */
            n_events: number;
            /**
             * N Spans
             * @default 0
             */
            n_spans: number;
            /**
             * Trace Ok
             * @default true
             */
            trace_ok: boolean;
            /** Trace Problems */
            trace_problems?: string[];
            /** Stages */
            stages?: components["schemas"]["StageStat"][];
            /** Models */
            models?: components["schemas"]["ModelStat"][];
            usage?: components["schemas"]["Usage"];
            /** Cache Hit Ratio */
            cache_hit_ratio?: number | null;
            /** Cost */
            cost?: number | null;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
            /**
             * N Llm Calls
             * @default 0
             */
            n_llm_calls: number;
            /**
             * N Tool Calls
             * @default 0
             */
            n_tool_calls: number;
            /**
             * Llm Errors
             * @default 0
             */
            llm_errors: number;
            /**
             * Llm Retries
             * @default 0
             */
            llm_retries: number;
            /**
             * Schema Retries
             * @default 0
             */
            schema_retries: number;
            /**
             * Replayed Calls
             * @default 0
             */
            replayed_calls: number;
        };
        /** RunPaused */
        RunPaused: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.paused";
            /** Checkpoint Id */
            checkpoint_id: string;
        };
        /** RunStarted */
        RunStarted: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
            /** Session Id */
            session_id: string;
            /** Pipeline */
            pipeline: string;
            /**
             * Schema Version
             * @default 1.2
             */
            schema_version: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "created" | "running" | "awaiting_user" | "succeeded" | "failed" | "cancelled";
        /**
         * RunView
         * @description 面向用户端的运行视图（不含内部阶段快照）。
         */
        RunView: {
            /** Id */
            id: string;
            /** Session Id */
            session_id: string;
            /** Pipeline */
            pipeline: string;
            status: components["schemas"]["RunStatus"];
            /** Created At */
            created_at: number;
            /** Started At */
            started_at?: number | null;
            /** Finished At */
            finished_at?: number | null;
            error?: components["schemas"]["ErrorInfo"] | null;
            /** Checkpoint */
            checkpoint?: {
                [key: string]: unknown;
            } | null;
        };
        /** Scope */
        Scope: {
            grade?: components["schemas"]["Slot_int_"] | null;
            semester?: components["schemas"]["Slot_str_"] | null;
            units?: components["schemas"]["Slot_list_str__"] | null;
            lesson_ids?: components["schemas"]["Slot_list_str__"] | null;
            kp_ids?: components["schemas"]["Slot_list_str__"] | null;
            /** Kp Topics */
            kp_topics?: {
                [key: string]: string;
            };
            topics?: components["schemas"]["Slot_list_str__"] | null;
        };
        /** Section */
        Section: {
            /** Id */
            id: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /** Items */
            items?: components["schemas"]["Item"][];
        };
        /**
         * SegmentInfo
         * @description 提示词分段（缓存友好布局：static → stable → history → dynamic）。
         */
        SegmentInfo: {
            /** Name */
            name: string;
            /** Chars */
            chars: number;
            /** Hash */
            hash: string;
        };
        /** Session */
        Session: {
            /** Id */
            id: string;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** SessionState */
        SessionState: {
            session: components["schemas"]["Session"];
            /** Messages */
            messages: components["schemas"]["Message"][];
            paper?: components["schemas"]["Paper"] | null;
            /** Active Run Id */
            active_run_id?: string | null;
        };
        /** SetMeta */
        SetMeta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_meta";
            /** Key */
            key: string;
            /** Value */
            value: unknown;
        };
        /** SetTitle */
        SetTitle: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_title";
            /** Title */
            title: string;
        };
        /** Slot[Action] */
        Slot_Action_: {
            value: components["schemas"]["Action"];
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[SourceMode] */
        Slot_SourceMode_: {
            value: components["schemas"]["SourceMode"];
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[dict[Tier, float]] */
        Slot_dict_Tier__float__: {
            /** Value */
            value: {
                [key: string]: number;
            };
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[int] */
        Slot_int_: {
            /** Value */
            value: number;
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[list[ItemKind]] */
        Slot_list_ItemKind__: {
            /** Value */
            value: components["schemas"]["ItemKind"][];
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[list[int]] */
        Slot_list_int__: {
            /** Value */
            value: number[];
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[list[str]] */
        Slot_list_str__: {
            /** Value */
            value: string[];
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Slot[str] */
        Slot_str_: {
            /** Value */
            value: string;
            /** @default default */
            origin: components["schemas"]["Origin"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "novel" | "template" | "edited";
        /**
         * SourceMode
         * @enum {string}
         */
        SourceMode: "auto" | "novel" | "template";
        /** SpanFinished */
        SpanFinished: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default debug */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "span.finished";
            kind: components["schemas"]["SpanKind"];
            /** Name */
            name: string;
            status: components["schemas"]["SpanStatus"];
            /** Duration Ms */
            duration_ms: number;
            /** Attrs */
            attrs?: {
                [key: string]: unknown;
            };
            error?: components["schemas"]["ErrorInfo"] | null;
        };
        /**
         * SpanKind
         * @enum {string}
         */
        SpanKind: "run" | "stage" | "llm" | "tool" | "check" | "other";
        /** SpanStarted */
        SpanStarted: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default debug */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "span.started";
            kind: components["schemas"]["SpanKind"];
            /** Name */
            name: string;
            /** Attrs */
            attrs?: {
                [key: string]: unknown;
            };
        };
        /**
         * SpanStatus
         * @enum {string}
         */
        SpanStatus: "ok" | "error" | "cancelled";
        /** StageStat */
        StageStat: {
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** Total Ms */
            total_ms: number;
            /** Max Ms */
            max_ms: number;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "consolidate" | "variation" | "integrated";
        /** ToolCall */
        ToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        };
        /** TurnAccepted */
        TurnAccepted: {
            /** Session Id */
            session_id: string;
            /** Run Id */
            run_id: string;
            /** Message Id */
            message_id: string;
        };
        /** Understanding */
        Understanding: {
            route: components["schemas"]["Route"];
            brief?: components["schemas"]["Brief"] | null;
            clarify?: components["schemas"]["ClarifyRequest"] | null;
            edit?: components["schemas"]["EditIntent"] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Chips */
            chips?: components["schemas"]["Chip"][];
            /**
             * Method
             * @default llm
             * @enum {string}
             */
            method: "llm" | "rules" | "rules_fallback";
            /** Notes */
            notes?: string[];
        };
        /**
         * UnderstandingReady
         * @description 需求理解完成：用户端据此展示"本次假设"芯片与路由结果（1.1 新增）。
         */
        UnderstandingReady: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default user */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "understanding.ready";
            understanding: components["schemas"]["Understanding"];
        };
        /** Usage */
        Usage: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Cached Tokens
             * @default 0
             */
            cached_tokens: number;
            /**
             * Reasoning Tokens
             * @default 0
             */
            reasoning_tokens: number;
        };
        /** UsageUpdate */
        UsageUpdate: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Ts
             * @default 0
             */
            ts: number;
            /** @default debug */
            visibility: components["schemas"]["Visibility"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "usage.update";
            usage: components["schemas"]["Usage"];
            /** Cost */
            cost?: number | null;
            /**
             * Currency
             * @default CNY
             */
            currency: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verification */
        Verification: {
            /** @default pending */
            status: components["schemas"]["VerifyStatus"];
            /** Checks */
            checks?: components["schemas"]["CheckResult"][];
        };
        /**
         * VerifyStatus
         * @enum {string}
         */
        VerifyStatus: "pending" | "verified" | "checked" | "needs_review" | "rejected";
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "user" | "debug";
        /** WarmupOut */
        WarmupOut: {
            /** State */
            state: string;
            /** Last Age S */
            last_age_s?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    warmup_api_warmup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarmupOut"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_turn_api_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_turn_api_sessions__session_id__turns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_paper_api_sessions__session_id__paper_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperPatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_paper_api_sessions__session_id__paper_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redo_paper_api_sessions__session_id__paper_redo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_paper_api_sessions__session_id__paper_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_history_api_sessions__session_id__paper_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_at_api_sessions__session_id__paper_revisions__rev__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                rev: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_diff_api_sessions__session_id__paper_diff_get: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paper_figure_api_sessions__session_id__figures__figure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                figure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 图形的 SVG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_refs_api_knowledge_refs_get: {
        parameters: {
            query: {
                ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_paper_file_api_sessions__session_id__export_post: {
        parameters: {
            query?: {
                inline?: boolean;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportOptions"];
            };
        };
        responses: {
            /** @description 导出的文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_checkpoint_api_runs__run_id__checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_runs_api_debug_runs_get: {
        parameters: {
            query?: {
                status?: string | null;
                session_id?: string | null;
                limit?: number;
                offset?: number;
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRunItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_run_api_debug_runs__run_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_events_api_debug_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["RunStarted"] | components["schemas"]["RunFinished"] | components["schemas"]["RunPaused"] | components["schemas"]["SpanStarted"] | components["schemas"]["SpanFinished"] | components["schemas"]["Progress"] | components["schemas"]["MessageDelta"] | components["schemas"]["MessageDone"] | components["schemas"]["ItemStatus"] | components["schemas"]["ItemDelivered"] | components["schemas"]["PaperPatched"] | components["schemas"]["CheckpointRequested"] | components["schemas"]["UnderstandingReady"] | components["schemas"]["LLMCall"] | components["schemas"]["RetrievalResult"] | components["schemas"]["UsageUpdate"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_stream_api_debug_runs__run_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
                token?: string | null;
            };
            header?: {
                "last-event-id"?: string | null;
                "x-debug-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_kp_api_debug_kp__kp_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path: {
                kp_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_badcases_api_debug_badcases_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Badcase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_add_badcase_api_debug_badcases_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BadcaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Badcase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_metrics_api_debug_metrics_get: {
        parameters: {
            query?: {
                limit?: number;
                token?: string | null;
            };
            header?: {
                "x-debug-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
